config/routes.rb
Rails.application.routes.draw do

  resources :airlines

  resources :flights do
    resources :passengers
  end

  root 'flights#index'

end

app/models/airline.rb
class Airline < ActiveRecord::Base
	has_many :flights, dependent: :destroy
	validates :name, presence: true, length: { minimum: 3 }
end

app/models/arrival.rb
# == Schema Information
#
# Table name: arrivals
#
#  id         :integer          not null, primary key
#  flight_id  :integer
#  date       :datetime
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Arrival < ActiveRecord::Base
  belongs_to :flight
  enum status: [:closed, :on_time, :landing, :landed]
end

app/models/departure.rb
# == Schema Information
#
# Table name: departures
#
#  id         :integer          not null, primary key
#  flight_id  :integer
#  date       :datetime
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Departure < ActiveRecord::Base
  belongs_to :flight
  enum status: [:closed, :on_gate, :boarding, :took_off]
  #enum status: ["closed", "on_gate", "boarding", "took_off"]

end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id         :integer          not null, primary key
#  number     :integer
#  airline_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Flight < ActiveRecord::Base
  belongs_to :airline
  has_one :departure, dependent: :destroy
  has_one :arrival, dependent: :destroy
  has_many :passengers, dependent: :destroy

  validates :airline, presence: true
  validates_numericality_of :number, only_integer: true, greater_than: 0

  accepts_nested_attributes_for :departure, :arrival
end

app/models/passenger.rb
# == Schema Information
#
# Table name: passengers
#
#  id         :integer          not null, primary key
#  flight_id  :integer
#  name       :string
#  passport   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Passenger < ActiveRecord::Base
  belongs_to :flight
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  def index
  	@airlines = Airline.all
  end

  def new
  	@airline = Airline.new
  end

  def create
  	@airline = Airline.new(airline_params)
  	if @airline.save
  		redirect_to airlines_path
  	else
  		render 'new'
  	end
  end

  def edit
  	@airline = Airline.find(params[:id])
  end

  def update
  	@airline = Airline.find(params[:id])
  	if @airline.update(airline_params)
  		redirect_to airlines_path
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@airline = Airline.find(params[:id])
  	@airline.destroy
  	redirect_to airlines_path
  end

  private
  	def airline_params
  		params.require(:airline).permit(:name)

  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  	@flights = Flight.all
  end

  def new
  	@flight = Flight.new
    @flight.departure = Departure.new
    @flight.arrival = Arrival.new
  end

  def create
  	@flight = Flight.new(flight_params)
  	if @flight.save
  		redirect_to flights_path
  	else
  		render 'new'
  	end
  end

  def edit
  	@flight = Flight.find(params[:id])
  end

  def update
  	@flight = Flight.find(params[:id])
  	if @flight.update(flight_params)
  		redirect_to flights_path
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@flight = Flight.find(params[:id])
  	@flight.destroy
  	redirect_to flights_path

  end

  private
  	def flight_params
  		params.require(:flight).permit(:airline_id, :number, departure_attributes: [:flight_id, :date, :status], arrival_attributes: [:flight_id, :date, :status])
  	end

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

  def index
    @passengers = Flight.find(params[:flight_id]).passengers

  end

  def show
    @passenger = Passenger.find(params[:id])
  end

  def new
    @passenger = Passenger.new
    @flight = Flight.find(params[:flight_id])
  end

  def create
    @passenger = Passenger.new(passenger_params)
    @passenger.flight_id = Flight.find(params[:flight_id]).id
    if @passenger.save
      redirect_to flight_passengers_path(params[:flight_id])
    else
      render 'new'
    end
  end

  def edit
    @passenger = Passenger.find(params[:id])
    @flight = Flight.find(params[:flight_id])
  end

  def update
    @passenger = Passenger.find(params[:id])
    if @passenger.update(passenger_params)
      redirect_to flight_passenger_path(params[:flight_id], @passenger.id)
    else
      render 'edit'
    end
  end

  def destroy
    @passenger = Passenger.find(params[:id])
    @passenger.destroy
    redirect_to flight_passengers_path(params[:flight_id])
  end


  private
    def passenger_params
      params.require(:passenger).permit(:name, :passport)
    end

end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/airlines/_form.html.erb
<div class='container well col-md-4'>
  <%= form_for @airline do |f| %>

    <% if @airline.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@airline.errors.count, "error") %> prohibited this airline from being saved:
        </h2>
        <ul>
          <% @airline.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, class:"form-control" %>
    </p>
    <p>
      <%= f.button :submit => "", class:"btn btn-success" %>
    </p>

  <% end %>

</div>

app/views/airlines/edit.html.erb
<h1>Edit Airline</h1>

<%= render 'form' %>

app/views/airlines/index.html.erb
<h1>Airlines</h1>

<table class="table table-striped text-center">
	<thead>
		<th class="text-center">Airline</th>
		<th class="text-center"># Flights</th>
		<th class="text-center">Edit | Delete</th>
	</thead>

	<% @airlines.each do |airline| %>
		<tr>
			<td><%= airline.name %></td>
			<td><%= Flight.where(airline_id: airline.id).count %></td>
			<td><%= link_to "Edit", edit_airline_path(airline) %> | <%= link_to "Delete", airline_path(airline), method: :delete %></td>
		</tr>
	<% end %>
</table>

<%= link_to	"Create Airline", new_airline_path, class:"btn btn-success" %>

app/views/airlines/new.html.erb
<h1>Create an Airline</h1>

<%= render 'form' %>

app/views/flights/_form.html.erb
<div class="well col-md-6">
  <%= form_for @flight do |f| %>

    <% if @flight.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:
        </h2>
        <ul>
          <% @flight.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

   <p>
   	<%= f.label "Airline name: " %>
   	<%= f.collection_select(:airline_id, Airline.all, :id, :name) %>
   </p>
    <p>
      <%= f.label "Flight number: " %>
      <%= f.number_field :number %>
    </p>
    <hr>
     <h2>Departure:</h2>
        <%= f.fields_for :departure do |departure| %>
        <%= departure.label :date %><br>
        <%= departure.datetime_select :date %><br>
        <%= departure.label :status%><br>
        <%= departure.select :status, Departure.statuses.keys.to_a %>
      <% end %>
      <hr>
      <h2>Arrival:</h2>
        <%= f.fields_for :arrival do |arrival| %>
        <%= arrival.label :date %><br>
        <%= arrival.datetime_select :date %><br>
        <%= arrival.label :status%><br>
        <%= arrival.select :status, Arrival.statuses.keys.to_a %>
      <% end %>
      <hr>
    <p>
      <%= f.button :submit => "", class:'btn btn-success' %>
    </p>

  <% end %>
</div>

app/views/flights/edit.html.erb
<h1>Update your flight</h1>

<%= render 'form' %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<table  class="table table-striped text-center">
	<thead>
		<th class="text-center col-md-1">Flight Number</th>
		<th class="text-center col-md-1">Airline</th>
		<th class="text-center col-md-1">Passengers</th>
		<th class="text-center col-md-1">Add Passenger</th>
		<th class="text-center col-md-2">Departure time</th>
		<th class="text-center col-md-1">Status</th>
		<th class="text-center col-md-2">Arrival time</th>
		<th class="text-center col-md-1">Status</th>
		<th class="text-center col-md-2">Update | Delete</th>
	</thead>

	<% @flights.each do |flight| %>
		<tr>
			<td><%= flight.number %></td>
			<td><%= flight.airline.name %></td>
			<td><%= link_to flight.passengers.count, flight_passengers_path(flight) %></td>
			<td><%= link_to "Add passenger", new_flight_passenger_path(flight) %></td>
			<td><%= flight.departure.date.strftime("%H:%M %d-%b-%Y") %></td>
			<td><%=flight.departure.status %></td>
			<td><%= flight.arrival.date.strftime("%H:%M %d-%b-%Y") %></td>
			<td><%= flight.arrival.status %></td>
			<td><%= link_to "Update", edit_flight_path(flight) %> | <%= link_to "Cancel", flight_path(flight), method: :delete %></td>
		</tr>
	<% end %>
</table>

<%= link_to	"New flight", new_flight_path, class:"btn btn-success" %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airport2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
       <%=link_to "Heathrow", root_path, class:"navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Airlines", airlines_path %></li>
          <li><%= link_to "Flights", flights_path %></li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/passengers/_form.html.erb
<div class="well col-md-6">
  <%= form_for [@flight, @passenger] do |f| %>

    <% if @passenger.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@passenger.errors.count, "error") %> prohibited this passenger from being saved:
        </h2>
        <ul>
          <% @passenger.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

   <p>
    <%= f.label "Name: " %>
    <%= f.text_field :name, class:'form-control' %>
   </p>
    <p>
      <%= f.label "Passport: " %>
      <%= f.number_field :passport, class:'form-control' %>
    </p>

      <p>
      <%= f.button :submit => "", class:'btn btn-success' %>
    </p>
  <% end %>
</div>

app/views/passengers/edit.html.erb
<h1>Edit passenger for flight: <%= @flight.number %> </h1>

<%= render 'form' %>

app/views/passengers/index.html.erb
<h1>Passengers' list</h1>

<div class="container">
  <div class="well col-md-4">
    <ol>
      <% @passengers.each do |passenger| %>

      <li><%= link_to passenger.name, flight_passenger_path(passenger.flight.id, passenger) %>
        </li>
      <% end %>
    </ol>
  </div>
</div>

<%= link_to "Add passenger", new_flight_passenger_path(params[:flight_id]), class:"btn btn-success" %> <br>

app/views/passengers/new.html.erb
<h1>New passenger for flight: <%= @flight.number %> </h1>

<%= render 'form' %>

app/views/passengers/show.html.erb
<h1>Passenger info</h1>

<div class="container">
  <div class="well col-md-4">
    <h3>Name :</h3>
    <%= @passenger.name %>
    <h3>Passport:</h3>
    <%= @passenger.passport %>
    <h3>Flight:</h3>
    <%= @passenger.flight.number %><br>
  </div>
</div>

<%= link_to "Passengers list", flight_passengers_path(params[:flight_id]), class:"btn btn-success" %>
<%= link_to "Edit", edit_flight_passenger_path(params[:flight_id],@passenger.id), class:"btn btn-info"%>
<%= link_to "Delete", flight_passenger_path(params[:flight_id],@passenger.id), method: :delete, class:"btn btn-danger" %>